### PR TITLE
Support for replacing a response by a new one

### PR DESCRIPTION
**Pull request by mathieucarbou**

### CODE REVIEW

**Comment by mathieucarbou** [comment]
This really simple PR allows for a very nice feat: ability to override a previously prepared response, in order tp build a new one.

the real sending will happen once the handle exist, not in the send method anymore.

**Comment by mathieucarbou** [comment]
@DRSDavidSoft: FYI

**Comment by DRSDavidSoft** [comment]
@mathieucarbou Wow, this is some excellent addition! How does it work internally? Also, what was the previous behavior, for reference?

Thanks for adding this too! 👍🏻

**Comment by mathieucarbou** [comment]
> @mathieucarbou Wow, this is some excellent addition! How does it work internally? Also, what was the previous behavior, for reference?

Look at the code ;-)

**Pull request merged**
