### PR TITLE
Strings literals (copy of #54)

### PR DESCRIPTION
**Pull request by mathieucarbou**
Copy of PR #54, rebased with linear history

### CODE REVIEW

**Comment by mathieucarbou** [comment]
@vortigont : thanks a lot for this big cleanup! I've reviewed. looks good, I am merging in the the dev branch this time and will test and will release after.

How much did you test on your side ?

Thanks!

**Comment by vortigont** [comment]
Hi! Thanks for looking into this. I'm running this on my project - esp32/esp32-s3 with websockets and some static files serving, not a super heavy setup, but works for me :) 8266 family not tested actually due to lack of those boards in possession now.
Let's see if it won't break anything, hope when this all will settle a little it would be easier to maintain the code and introduce new features if any.
Cheers!

**Comment by mathieucarbou** [comment]
It is merged and released!

I also took the opportunity to rename the lib as per the Arduino library manager requirements

**Comment by vortigont** [comment]
Nice! Renaming the lib is good thing to do, would be easier to resolve conflicts with other 3rd party libs depended on AsyncServer. Could simply put original AsyncServer into platformio's `lib_ignore`.
Thanks!

**Pull request merged**
