### PR TITLE
Cleanups and speed / memory improvements

### PR DESCRIPTION
**Pull request by mathieucarbou**

### CODE REVIEW

**Comment by mathieucarbou** [comment]
@vortigont: FYI I have opened this PR to introduce overloaded methods with `const char*`: this should avoid more heap usage caused by String copy: there are many times when we pass a direct string constant in parameter (such as content types or parameter names). This were converted to String, and the the String object passed in ref through the call stack up to the point where it was copied again into a class variable.

**Comment by vortigont** [comment]
Nice work indeed! Had an idea about the same, those string overloads results in a code size overhead also.
Had to rework one of my projects in the same manner when deprecated esp8266 code.
It was mostly there for 8266 flashstrings.

With some efforts investment it is possible to replace it even with `= NULL`, but need more careful refactoring in function code. Maybe someday...

**Comment by mathieucarbou** [comment]
Thanks! If you are happy, I will merge ;-) I have tested in a project.

**Comment by mathieucarbou** [comment]
Oh! but you also have the rights to review and merge now, I forgot ;-)

**Comment by vortigont** [comment]
> Oh! but you also have the rights to review and merge now, I forgot ;-)

Ah! True! Need to get used to it :) Do you want me to update it with suggested expr?

**Comment by mathieucarbou** [comment]
> > Oh! but you also have the rights to review and merge now, I forgot ;-)
> 
> Ah! True! Need to get used to it :) Do you want me to update it with suggested expr?

I didn't get what you meant by = Null.
But yes go ahead you can add a new commit to my branch it is opened:-)

Please Make sure that everything is backward compatible though;-)

**Comment by vortigont** [comment]
> I didn't get what you meant by = Null.

won't do this for now. Need more careful review.
I'll try to explain the idea
for ex we have a method where `content` has a default  `const char*` argument
```
    AsyncWebServerResponse* beginResponse(int code, const char* contentType = asyncsrv::empty, const char* content = asyncsrv::empty, AwsTemplateProcessor callback = nullptr);
```

Need to pass it some real `const char*` pointer even if it points to an empty sting `""`, i.e. a NULL somewhere in ROM.
Can we replace it with NULL pointer - `const char* content = NULL`?
For that need to know how this arg is processed later on, let's see

```
AsyncWebServerResponse* AsyncWebServerRequest::beginResponse(int code, const char* contentType, const char* content, AwsTemplateProcessor callback) {
  if (callback)
    return new AsyncProgmemResponse(code, contentType, (const uint8_t*)content, strlen(content), callback);
  return new AsyncBasicResponse(code, contentType, content);
}
```

the evil is here `strlen(content)` - `strlen` can't handle NULLs  correctly and it will boom. The option is to replace it with C11's `strnlen_s` and some high enough content size we are safe to handle at all. We can also make code more safe this way.

Let's put it in TODO list.

**Comment by vortigont** [comment]
yep! LGTM! pls merge. Nice done!

**Review by vortigont — APPROVED** [review]
LGTM!

**Pull request merged**
