### PR TITLE
MessagePack Support (Fix #59)

### LINKED ISSUE #59: [F] Message Pack support (`AsyncMessagePackResponse ` similar to `AsyncJsonResponse`)
Like `AsyncJsonResponse`, `AsyncMessagePackResponse`  would support message pack through ArduinoJson and set the proper content-type `application/msgpack`

Original discussion: https://github.com/mathieucarbou/ESPAsyncWebServer/discussions/48#discussioncomment-10082335

### PR DESCRIPTION
**Pull request by mathieucarbou**

### CODE REVIEW

**Comment by mathieucarbou** [comment]
Message pack being only supported over https on a majority of browsers, we see errors like that when requesting an endpoint outputting message pack content type:

image

The value for this library is thus limited since https support is limited (not possible for esp32).

Will merge if people like / still want it

**Comment by mathieucarbou** [comment]
FYI @vortigont @proddy

**Comment by vortigont** [comment]
I guess it makes sense when used over WebSocket only then, no? This https madness everywhere is like a snake eating it's own tail.

**Comment by mathieucarbou** [comment]
> I guess it makes sense when used over WebSocket only then, no? This https madness everywhere is like a snake eating it's own tail.

It is also possible to use send/receive binary `Uint8Array` (`application/octet-stream`) through Ajax.
My guess is that this use case might be valid since won't go through any proxy, but I didn't test it.

I would like @proddy to explain his use case before merging.

**Comment by proddy** [comment]
Thanks for looking into this. My use case is I'm sending back large amounts of data in one block that gets rendered into a table in the browser. You can see a live demo at https://ems-esp.derbyshire.nl (any username/password will be accepted). 

That data is not streamed, chunked or paginated (although it could be). It's just compressed using msgpack and saves more than 30% in payload size. My web code is react/typescript/mui and I use Alova (much faster than Axios) to send the compressed msgpack data in a binary`arraybuffer` (https://github.com/emsesp/EMS-ESP32/blob/9c20e93b3c49887b285da1e657190e0f0722b332/interface/src/project/api.ts#L24)

I don't need to use the content-type `application/msgpack` as it's all handled internally.

My solution now was to adjust AsyncWS and AsyncJson to take a new parameter indicating if it is compressed (msgpack) or not. It's just a few extra lines, dirty but it works. My implementation of AsyncWS is optimized for ESP32 for speed and memory, and has some other changes specific to my project.

**Comment by mathieucarbou** [comment]
> Thanks for looking into this. My use case is I'm sending back large amounts of data in one block that gets rendered into a table in the browser. You can see a live demo at https://ems-esp.derbyshire.nl (any username/password will be accepted).
> 
> That data is not streamed, chunked or paginated (although it could be). It's just compressed using msgpack and saves more than 30% in payload size. My web code is react/typescript/mui and I use Alova (much faster than Axios) to send the compressed msgpack data in a binary`arraybuffer` (https://github.com/emsesp/EMS-ESP32/blob/9c20e93b3c49887b285da1e657190e0f0722b332/interface/src/project/api.ts#L24)
> 
> I don't need to use the content-type `application/msgpack` as it's all handled internally.
> 
> My solution now was to adjust AsyncWS and AsyncJson to take a new parameter indicating if it is compressed (msgpack) or not. It's just a few extra lines, dirty but it works. My implementation of AsyncWS is optimized for ESP32 for speed and memory, and has some other changes specific to my project.

Thanks! 

That's interesting! So the use case falls into what I was envisioning: these are ajax calls transmitting binary data. Like what it done for WS too.

So I think I will merge this PR, but probably will release a new version later, except if someone is in hurry to use it.

**Comment by mathieucarbou** [comment]
> My implementation of AsyncWS is optimized for ESP32 for speed and memory,

Would be glad to know if some of these improvements could be ported in this fork 👍

**Comment by vortigont** [comment]
That's a really nice project [EMS-ESP32](https://github.com/emsesp/EMS-ESP32) indeed. Oh I wish I could have that knowledge of react to build such a nice UIs. Have my own UI lib based on WS but it far more ugly and cumbersome :(

**Pull request merged**
