### PR TITLE
update readme on build options

### PR DESCRIPTION
**Pull request by vortigont**

### CODE REVIEW

**Review by mathieucarbou — APPROVED** [review]

**Comment by mathieucarbou** [comment]
@vortigont : when we modify the readme, we must also copy all it's content to the index.md file in the doc folder : this part is the source of the website. I didn't do an automatic job yet.
Thanks!

**Comment by mathieucarbou** [comment]
Also, if you want, why not adding a section called maintainers with 2 bullet points with our GitHub IDs and link to profiles 

Also, the library.json ça be updated: you could add your user is to the maintainers 

Something like 

-----

## Maintainers 

- [@mathieucarbou](https://github.com/mathieucarbou)
- [@vortigont](https://github.com/vortigont)

**Comment by vortigont** [comment]
Hey, @mathieucarbou 
thanks! I've updated a bit readme file and copied it to `docs/index.md` as-is. Hope this should be fine!

**Review by mathieucarbou — APPROVED** [review]

**Comment by mathieucarbou** [comment]
Awesome, thanks!

**Pull request merged**
